### ISSUE TITLE
Allow uploading signatures with scp

### ISSUE THREAD

**Issue by xeqi** [ato/clojars-web#118]
Currently signatures can only be sent over https.  It would be nice to allow them to come from scp as well.

This will require matching the signatures with the other files, upgrading pomegranate, and using the newer deployment functions.

**Comment by tobias** [comment]
scp uploads have been disabled for a while, and were removed from the codebase via https://github.com/ato/clojars-web/commit/dea1b0874fde442b5b776f4fd4d95a51b33b1051. Closing.
