### ISSUE TITLE
Delete the 'twashing1' user

### ISSUE THREAD

**Issue by twashing** [ato/clojars-web#159]
Created an extraneous user while trying debug my existing one. Don't want to leave accounts in a cluttered state. So admins can go ahead and remove the user: ***twashing1***

Thanks

**Comment by tobias** [comment]
I realize this issue has been open for quite a while, most likely because deleting users takes a bit of work. Since there's no critical need to delete the user account, my preference is to leave it. 

I'm closing this issue, but feel free to reopen if you disagree or want to discuss further.

**Comment by twashing** [comment]
Okie dokes. Thanks for cleaning that up.

Tim Washington
Interruptsoftware.com <http://interruptsoftware.com>
416.843.9060
