### ISSUE TITLE
clojars.org css styles considered to be text/plain by some browsers

### ISSUE THREAD

**Issue by mnicky** [ato/clojars-web#183]
Some browsers (e.g Opera or some versions of MSIE) consider the css style files of clojars.org to be of _text/plain_ mime type. As a consequence, the site is displayed without any styling...

E.g. this is how it looks in Opera 12.16 under Debian Squeeze: http://i.imgur.com/6Ble7NL.png or MSIE 11 under Win 7: http://i.imgur.com/mmmeorS.png

And this is screenshot from Opera's Dragonfly developer tool: http://i.imgur.com/kbHQ5WT.png

Potential cause can be a server misconfiguration...

**Comment by beppu** [comment]
@tobias - My memory is fuzzy on this, but I think you said that the production deployment of clojars-web was running behind nginx.  If we could see the nginx config, this should be a really easy thing to fix.

**Comment by tobias** [comment]
@beppu - yes, clojars is fronted by nginx. The relevant portion of the nginx config is likely: 

```
location /stylesheets {
    expires 4h;
    proxy_pass http://clojars-web;
}
```

You can see the full config here: https://gist.github.com/tobias/fc3bb56be42c7c9576bb

**Comment by beppu** [comment]
Let's change that block to:

```nginx
location /stylesheets {
    expires 4h;
    proxy_pass http://clojars-web;
    add_header Content-Type text/css;
}
```

**Comment by tobias** [comment]
@beppu - thanks! That did the trick:

```
$ curl -I https://clojars.org/stylesheets/screen.css                                                                                                                                                                            master 0d964f9
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 21 Sep 2015 13:50:44 GMT
Content-Length: 8785
Connection: keep-alive
Last-Modified: Fri, 04 Sep 2015 13:37:41 GMT
Expires: Mon, 21 Sep 2015 17:50:44 GMT
Cache-Control: max-age=14400
Content-Type: text/css
```
