### ISSUE TITLE
Getting feedback on "could not verify signature"?

### ISSUE THREAD

**Issue by mikera** [ato/clojars-web#234]
I'm trying to deploy verified, signed artifacts to Clojars but keep getting "Could not verify signature" messages. see e.g.

https://clojars.org/net.mikera/core.matrix

I'm at a dead end on this: I think my PGP public keys are all in my profile but can't figure out what is going wrong.

Any thoughts? Or any way to get more diagnostic information so I can solve the problem?

**Comment by paulrd** [comment]
I've been having the same issue.

**Comment by tobias** [comment]
Clojars is now using clj-pgp (#287) -  @mikera, @paulrd: are either of you still seeing this issue?

**Comment by mikera** [comment]
Deploying to clojars has been working fine for me so far

**Comment by paulrd** [comment]
Yes! It works for me now!

**Comment by tobias** [comment]
Thanks! Closing.
