### ISSUE TITLE
Cannot deploy snapshot versions using lein-repack

### ISSUE THREAD

**Issue by zcaudate** [ato/clojars-web#263]
When I deploy a snapshot version of hara to clojars using lein repack deploy, there is a message that says `server out of keys`. However, if I deploy an official version, it works.

**Comment by tobias** [comment]
Is this still an issue? Is there more to the message?

**Comment by zcaudate** [comment]
I haven't tried it after that time as I've just continuously deployed to releases. It's not an issue as I've worked around it. However it is just a curiousity,  I'm wondering if there is anything different between the two repos

**Comment by tobias** [comment]
There isn't a separate repo for SNAPSHOTs, they go in to the same repo as releases.

I just tried `lein repack deploy` with a SNAPSHOT version of hara (with the group-id changed to 'org.clojars.tcrawley'), and they all deployed fine for me. 

I'm closing this issue, but feel free to reopen if you try a snapshot again and see the error.

**Comment by tobias** [comment]
The releases can be seen at https://clojars.org/groups/org.clojars.tcrawley

**Comment by zcaudate** [comment]
great! thanks for that
