### ISSUE TITLE
Documentation should mention naming conventions for projects

### ISSUE THREAD

**Issue by fdb** [ato/clojars-web#275]
I've spent two days searching why a couldn't deploy a project, only to find out that the name, "oscP5" is illegal. Changing it to "oscp5" (without the capital "P") works.

It would be nice if this was mentioned in the docs somewhere.

**Comment by danielcompton** [comment]
It would also be nice to give a specific error message to the user about what they're doing wrong when deploying.

**Comment by danielcompton** [comment]
https://maven.apache.org/guides/mini/guide-naming-conventions.html has the naming conventions. groupid must be a valid Java package name, artifactid needs to be lowercase letters

**Comment by tobias** [comment]
The conventions we enforce are at https://github.com/ato/clojars-web/tree/master/src/clojars/event.clj#L19. With http-based deploys, I'm not sure how much information we can convey to the client. It would be nice if we could trigger the client to present something other than a general failure message, but I haven't looked to see if this is possible.

**Comment by tobias** [comment]
related: #367 covers displaying better information to the user.

**Comment by giraffeinaspeedo** [comment]
Can this be closed as of b6fd245a6f948672ab7e226626c777e68a2394f9?

**Comment by tobias** [comment]
Yes, that commit and the updated [FAQ](https://github.com/ato/clojars-web/wiki/About#what-is-the-legal-format-for-a-group-or-project-name) should complete this. Thanks for the reminder!
