### ISSUE TITLE
Delete request: [potpuri "0.2.0"]

### ISSUE THREAD

**Issue by Deraen** [ato/clojars-web#286]
I accidentally pushed this without groupId: https://clojars.org/potpuri

Thanks!

**Comment by tobias** [comment]
Sorry for the delay - this artifact has been deleted.

**Comment by tobias** [comment]
Note that you still own the `potpuri` group - let us know if you want to give that up.

**Comment by Deraen** [comment]
I have no need for that, so yes, I can give that up.

Thanks.

**Comment by tobias** [comment]
The `potpuri` group has been deleted.
