### ISSUE TITLE
Delete Request for [com.danieldyba/f1-clj '0.0.1']

### ISSUE THREAD

**Issue by dyba** [ato/clojars-web#289]
Hello,

I would like to delete the several jars I deployed before I finally settled on a GroupId / ArtifactId. I need the following deleted:

* f1-clj/f1-clj
* com.danieldyba/f1-clj

I'm sticking with the final version: com.danieldyba/fellowship-one. Thank you!

**Comment by tobias** [comment]
Sorry for the delay - these artifacts have been deleted.

**Comment by tobias** [comment]
Note that you still own the f1-clj group - let us know if you want to give that up.

**Comment by dyba** [comment]
Thanks @tobias ! Go ahead and drop the f1-clj group.

**Comment by tobias** [comment]
The `f1-clj` group has been deleted.

**Comment by dyba** [comment]
:+1:
