### ISSUE TITLE
Deletion Request: cljsjs/reactjs

### ISSUE THREAD

**Issue by martinklepsch** [ato/clojars-web#290]
https://clojars.org/cljsjs/reactjs

This is now for consistency packaged as cljsjs/react.
To avoid confusion it would be great if it could be deleted.

**Comment by tobias** [comment]
Sorry for the delay - this artifact has been deleted.

**Comment by martinklepsch** [comment]
Awesome, thank you Toby!

On Friday, March 13, 2015, Toby Crawley <notifications@github.com> wrote:

> Sorry for the delay - this artifact has been deleted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ato/clojars-web/issues/290#issuecomment-79018812>.
>


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>
