### ISSUE TITLE
Deletion request: [restmonic-utils] (both releases)

### ISSUE THREAD

**Issue by evanspa** [ato/clojars-web#294]
I JUST uploaded this by accident, and would like it removed please.

Thank you,

-Paul

**Comment by tobias** [comment]
Sorry for the delay - this artifact has been deleted.

**Comment by tobias** [comment]
Note that you still own the restmonic-utils group - let me know if you want to give that up as well.

**Comment by evanspa** [comment]
Hi Toby,

Thank you.  Yes, you can also get rid of that group too.

-Paul

**Comment by tobias** [comment]
The `restmonic-utils` group has been deleted.
