### ISSUE TITLE
Delete Request

### ISSUE THREAD

**Issue by knusbaum** [ato/clojars-web#298]
Hey, there.

I'd like to delete the following:
org.cloujars.knusbaum.restarts

I was playing around with leiningen and didn't realize that it wasn't possible to delete projects without filing a ticket, so I was sort of careless and generated some trash.

That 'incubation period' ato mentioned in #9 would really be helpful.

**Comment by tobias** [comment]
The `org.cloujars.knusbaum.restarts` group has been deleted, along with all of its artifacts.

**Comment by knusbaum** [comment]
Thanks.
