### ISSUE TITLE
Recovering from forgotten passphrase

### ISSUE THREAD

**Issue by interstar** [ato/clojars-web#300]
OK. I know I'm an idiot. 

But I forgot the passphrase I used to allow gpg to sign the library I uploaded. 

I still have my Clojars site login. Is there anything I can do to refresh this? Eg. by creating a new signed identity on my machine and attaching this to the project? Or deleting the project / account on Clojars and recreating a new one (with same email address, but new identity?)

**Comment by interstar** [comment]
Although on second thoughts, maybe the reason I don't remember the passphrase for this is that I didn't actually sign it. Is there a way to confirm whether my Clojar is signed? (It's in the classic directory and not promoted) : https://clojars.org/com.alchemyislands/patterning/versions/0.3.0-SNAPSHOT

**Comment by tobias** [comment]
`lein` doesn't sign SNAPSHOT releases, so this release was not signed. In general, an easy way to determine (and verify) the signature of a dependency is to add it to a project and run `lein deps :verify`. 

If you've lost the passphrase for your private key, I believe your only recourse is to generate a new keypair and replace the public key in your account. I believe the key is only used to validate artifacts that are being promoted to the releases repo, but I'm not sure what the full impact of replacing the key is.

**Comment by interstar** [comment]
OK. Thanks. I will have to sit down and investigate that.
