### ISSUE TITLE
Change GitHub URL

### ISSUE THREAD

**Issue by strika** [ato/clojars-web#301]
I published a jar, but from a forked repository, so GitHub URL is wrong. Is there a way to change the URL?

Thanks.

**Comment by tobias** [comment]
To change the URL, you'll need to change it locally and push a new release. For git-based projects, lein detects the URL by looking at the `origin` remote in `.git/config`. You can either point the `origin` at the new repo, or override that auto-detection by adding:

```clojure
:scm {:name "git" :url "the url you want to use"}
```

to your `project.clj`. You can run `lein sample` to get more details about other `:scm` options.

**Comment by strika** [comment]
@tobias Thanks for your answer. But, I already have the `:scm` entry pointing to the repository I want - https://github.com/strika/clj-webdriver-boilerplate/blob/master/project.clj. Still the repository that is displayed on the Clojars page is the repository I deployed from, not the repository that's listed in `project.clj`.

**Comment by ato** [comment]
Looking at the project page:

https://clojars.org/clj-webdriver-boilerplate

The version deployed to clojars (commit 86ca15, linked top right on project page) is older and doesn't include the commit that changes the scm url (098285).

Before deploying you can run "lein pom" and check that Leiningen writes the desired url to pom.xml (that's the file Clojars reads the url from). If it's not correct then that would indicate a bug in Leiningen.
