### ISSUE TITLE
delete request: incomplete deploy of figwheel 2.5.0

### ISSUE THREAD

**Issue by bhauman** [ato/clojars-web#304]
I have an incomplete deploy of 

lein-figwheel 2.5.0
figwheel 2.5.0
figwheel-sidecar 2.5.0

Can you delete these por favor??

**Comment by tobias** [comment]
Just to confirm: do you mean version 0.2.5 instead of 2.5.0?

**Comment by bhauman** [comment]
0.2.5 yeah :)

**Comment by tobias** [comment]
Done.

**Comment by bhauman** [comment]
Thanks man!

**Comment by bhauman** [comment]
Are you closing these issues?

**Comment by tobias** [comment]
I will once I have the rights to :)
