### ISSUE TITLE
delete request (org.clojure.bill/lein-environ)

### ISSUE THREAD

**Issue by Bill** [ato/clojars-web#305]
Please delete the project:

* org.clojure.bill/lein-environ

I gave it a bad group id (containing "clojure" instead of "clojars").

Thanks.

**Comment by Bill** [comment]
Will you please delete the group too:

org.clojure.bill

(note it contains "clojure" instead of "clojars")

**Comment by tobias** [comment]
The `org.clojure.bill` group has been deleted, along with all of its artifacts.
