### ISSUE TITLE
can't deploy to clojars

### ISSUE THREAD

**Issue by dillonforrest** [ato/clojars-web#306]
Hi all! Thanks for clojars and all your hard work! I'm pumped to be deploying my own stuff to to clojars. :) I'm new to clojure and leiningen, and I couldn't find a similar pre-existing issue unfortunately. Please pardon my inexperience!

I just tagged version 0.1.0 of my library: https://github.com/dillonforrest/domshot

However, when I do `lein deploy clojars`, after I enter the passphrase to unlock my secret key, I get the following errors:

```
Sending domshot/domshot/0.0.1/domshot-0.0.1.pom (4k)
    to https://clojars.org/repo/
Could not transfer artifact domshot:domshot:pom:0.0.1 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/domshot/domshot/0.0.1/domshot-0.0.1.pom, ReasonPhrase: Forbidden.
Sending domshot/domshot/0.0.1/domshot-0.0.1.jar (1766k)
    to https://clojars.org/repo/
Could not transfer artifact domshot:domshot:jar:0.0.1 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/domshot/domshot/0.0.1/domshot-0.0.1.jar, ReasonPhrase: Forbidden.
Sending domshot/domshot/0.0.1/domshot-0.0.1.jar.asc (1k)
    to https://clojars.org/repo/
Could not transfer artifact domshot:domshot:jar.asc:0.0.1 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/domshot/domshot/0.0.1/domshot-0.0.1.jar.asc, ReasonPhrase: Forbidden.
Sending domshot/domshot/0.0.1/domshot-0.0.1.pom.asc (1k)
    to https://clojars.org/repo/
Could not transfer artifact domshot:domshot:pom.asc:0.0.1 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/domshot/domshot/0.0.1/domshot-0.0.1.pom.asc, ReasonPhrase: Forbidden.
Failed to deploy artifacts: Could not transfer artifact domshot:domshot:pom:0.0.1 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/domshot/domshot/0.0.1/domshot-0.0.1.pom, ReasonPhrase: Forbidden.
```

Notice also that it seems to be deploying version 0.0.1 instead of 0.1.0.

I followed all the instructions in `lein help gpg`, but I think I'm missing something else. What am I doing wrong?

**Comment by tobias** [comment]
Hi @dillonforrest: the version in your project.clj is still 0.0.1, which is what lein is using to build the release, and version 0.0.1 already exists on clojars. If you update your version to 0.1.0, the deploy should work. Let us know if it doesn't.

**Comment by dillonforrest** [comment]
omgawd yes, that was the problem. ~_____~;;;;

THANK YOUUUU!!!! :+1:
