### ISSUE TITLE
Hide references to scp deploys

### ISSUE THREAD

**Issue by tobias** [ato/clojars-web#308]
This would include hiding the ssh key field on profiles, and removing mention of scp deploys from the docs. This is assuming we want to get rid of of scp deploys altogether.

**Comment by danielcompton** [comment]
Can I help on this? It looks like it's just the docs that still need to be updated?

**Comment by tobias** [comment]
@danielcompton sure, thanks! Yes, I believe the only remaining piece is the docs.

**Comment by danielcompton** [comment]
There's references to SCP still in these places:

https://github.com/ato/clojars-web/wiki/POM
https://github.com/technomancy/leiningen/blob/master/doc/GPG.md
https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md

**Comment by tobias** [comment]
Thanks for finding those references.

> https://github.com/ato/clojars-web/wiki/POM

This page should probably have a notice at the top that it is
out-of-date, and you should use lein/boot/maven instead of
hand-rolling a pom. And we should drop it from the help topic
navigation on the right.

> https://github.com/technomancy/leiningen/blob/master/doc/GPG.md

I think the "lein deploy clojars vs. scp" paragraph can be dropped
completely.

> https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md

This doc is about deploying to places other than Clojars, and the SCP
section here covers deploying to your own repo using the SCP wagon. I
don't think we need to change anything here.

**Comment by danielcompton** [comment]
I saw the DEPLOY section was referring to other places, but I thought it might be good to just add a quick mention that SCP to Clojars isn't supported.

**Comment by danielcompton** [comment]
I think this can be closed off now.

**Comment by tobias** [comment]
Great, thanks!
