### ISSUE TITLE
Deletion Request

### ISSUE THREAD

**Issue by minikomi** [ato/clojars-web#311]
Please delete the [jughead](https://clojars.org/jughead) jar - I'm new to deploying clojars and I have created a version [namespaced at org.clojars](https://clojars.org/org.clojars.minikomi/jughead). Thanks!

**Comment by tobias** [comment]
You are welcome to use the jughead group for the jughead project. If you are certain you want to release it (potentially allowing someone else to claim it), let me know.

**Comment by tobias** [comment]
@minikomi do you still want this deleted?

**Comment by minikomi** [comment]
Yes thanks

**Comment by tobias** [comment]
The `jughead` group has been deleted, along with all of its artifacts.
