### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by ricardojmendez** [ato/clojars-web#312]
Hi,

Could you please delete [this non-canonical neocons fork](https://clojars.org/org.clojars.ricardojmendez/neocons)? It was only a temporary push to be able to share some fixes while they were released on the main neocons distribution, but they are already out - I'd rather nobody gets an unmaintained fork by mistake.

Thanks!

**Comment by tobias** [comment]
This artifact has been deleted.

**Comment by ricardojmendez** [comment]
Thanks @tobias
