### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by ctdean** [ato/clojars-web#313]
Please delete https://clojars.org/clams/versions/0.2.0  This was an accidental version naming.

**Comment by tobias** [comment]
Are you asking for a deletion of just version 0.2.0? Are you sure no one is using it? The standardtreasury/clams readme currently points to version 0.2.0, and there have already been a few downloads of that version.

**Comment by ctdean** [comment]
Yes, I'm sure.  No one outside of the initial testers is using it.

Thanks!

**Comment by tobias** [comment]
Version `0.2.0` of `clams` has been deleted.
