### ISSUE TITLE
Snapshot versions show incorrect errors

### ISSUE THREAD

**Issue by stumitchell** [ato/clojars-web#314]
Hi I noticed that if you upload a snapshot version you get all of the following issues

Promotion
Issues Blocking Promotion
Snapshot versions cannot be promoted
Missing file structural-caching-0.1.2-SNAPSHOT.jar
Missing file structural-caching-0.1.2-SNAPSHOT.pom
Missing description
Missing url
Missing licenses
Missing scm
/home/clojars/repo/structural-caching/structural-caching/0.1.2-SNAPSHOT/structural-caching-0.1.2-SNAPSHOT.jar is not signed.
/home/clojars/repo/structural-caching/structural-caching/0.1.2-SNAPSHOT/structural-caching-0.1.2-SNAPSHOT.pom is not signed.

This can lead the user to think that the files are not uploading when infact they are as when I uploaded a 0.1.1 version I did not get any errors

**Comment by tobias** [comment]
It looks like most of the warnings are caused by it looking for the jar and pom as `structural-caching-0.1.2-SNAPSHOT` instead of the timestamped files (ex: `structural-caching-0.1.2-20150401.034949-1.jar`). We should probably either limit the warnings list to "Snapshot versions cannot be promoted" or find the correct files for SNAPSHOTs. I'll take a look.

**Comment by stumitchell** [comment]
Yeah it looked like that to me too, but then I tried to use structural-caching 0.1.2-SNAPSHOT as a dependency and it didn't download. Did I do something wrong, I used the same command as when I uploaded 0.1.1

**Comment by tobias** [comment]
What error do you see when you depend on it? `lein deps :tree` downloads it for me when I depend on `[structural-caching "0.1.2-SNAPSHOT"]`.

**Comment by stumitchell** [comment]
yeah you are right must have been something I was doing wrong, sorry for the noise.

**Comment by tobias** [comment]
No problem!

**Comment by tobias** [comment]
The above commit just shows the SNAPSHOT message - all of the rest of the blocker messages are now suppressed.
