### ISSUE TITLE
Loading test data problem

### ISSUE THREAD

**Issue by dotemacs** [ato/clojars-web#316]
I tried to load test data, so that I could have a setup that matches live, in order to test some features, but stumbled upon an issue. See below.

After running, as per repo's README (I've combined the steps of bringing up the app and adding the test data):

    git clone https://github.com/ato/clojars-web.git
    cd clojars-web
    wget http://meshy.org/~ato/clojars-test-data.sql.gz
    mkdir -p data
    rm -f data/dev_db
    gunzip -c clojars-test-data.sql.gz | sqlite3 data/dev_db
    lein migrate
    lein ring server

and I try to search for a clojar, say **overtone** via the web interface on http://localhost:3000/

I get this stacktrace: https://gist.github.com/dotemacs/baca37ea297d9b65b9b1

The web interface just reports that it can't find the clojar I was after, looking like this: 

http://cl.ly/image/3c3O2d2u3E3z

with this URL in the address bar: http://localhost:3000/search?q=overtone

What step is missing in order to have the app in a state where the searches can be run?

Thanks

**Comment by dotemacs** [comment]
I'm seeing a lot of activity on this repo, lots of issues and pull requests getting addressed. Which is great. 

Maybe there would be even more contributions if this issue was resolved, allowing people to test their changes in a more realistic setup. Just an idea. Thanks

**Comment by tobias** [comment]
The search index is built from the .pom files, so you'll need at least a partial repo, and then need to generate an index via `clojars.search/-main`. I haven't actually done it myself, but will figure out the details and add it to the README when I get a chance.

**Comment by tobias** [comment]
@dotemacs Can you take a look at https://github.com/ato/clojars-web/#test-data and see if that does what you need?

**Comment by dotemacs** [comment]
Will do!
