### ISSUE TITLE
A project with '.' in its name can't deploy a SNAPSHOT

### ISSUE THREAD

**Issue by tobias** [ato/clojars-web#317]
Uploading the maven-metadata.xml for the version (not the project) results in a 400 error. This was introduced by https://github.com/ato/clojars-web/commit/2645e332a8ba835a2db6e0b43a872962bafdaaec#diff-aa3ebd0ac13743556a1f91be3ef1c6baL64, but I think it was just an accident that this worked at all, since the version-specific maven-metadata.xml should really be handled by the `/:group/:artifact/:version/:filename` route instead of `/:group/:artifact/:file`. 

@ato @technomancy: I'm happy to work up a fix that uses the correct route, but I'd love a review from one of you guys before it gets deployed to make sure I'm not screwing something up.

**Comment by tobias** [comment]
@ato @technomancy: does that change look good to you?

A side effect of that fix is it allows arbitrary xml files to be deployed to a version, but I don't think that is a problem.

**Comment by technomancy** [comment]
I have to admit I don't see how this fixes the problem described, but it looks like a fine change anyway. =)

**Comment by tobias** [comment]
Thanks @technomancy, and you're right, my commit doesn't really fix
the issue :)

That commit allows dot-named SNAPSHOTs by allowing the
"/:group/:artifact/:version/:filename" route to match .xml files,
since the version-specific metadata really belongs on that route. I
thought my change routed *all* of the version-specific
maven-metadata.xml's through that route, but upon review, I realize it
only routes maven-metadata.xml* for dot-named artifacts through that
route - maven-metadata.xml* for un-dotted SNAPSHOTs still go through
the "/:group/:artifact/:file" route, which is still a problem.

For example, a PUT to
`org/clojars/dantheman/test/maven-metadata.xml` matches the
non-versioned route with:

`{:group "org/clojars/dantheman" :artifact "test" :file "maven-metadata.xml"}`

and a request to `org/clojars/dantheman/test/0.0.3-SNAPSHOT/maven-metadata.xml`
matches the same route with:

`{:group "org/clojars/dantheman/test" :artifact "0.0.3-SNAPSHOT" :file "maven-metadata.xml"}

Which just happens to work because we only use :artifact as part of
the file path: `(io/file (config :repo) group artifact file)`, but the
artifact name being part of :group does result in the creation of
spurious groups, since we call `db/check-and-add-group` with the :group
that includes the artifact name
(see https://clojars.org/groups/lein-immutant.lein-immutant as an example).

The quick fix here isn't my earlier commit, but a revert of the change
to the :group regex in the "/:group/:artifact/:file" route (changing
`:group #"[^\.]+"` back to `:group #".+"`). That will allow dotted
SNAPHOTs to deploy again, but doesn't prevent the creation of spurious
groups. The real fix is to have the :version route handle all
versioned traffic, but that's a tougher nut to crack, since there is
no reliable way to differentiate an artifact name from a version
identifier. I'll open another issue for that and let this issue just
be for the regression that prevents dotted SNAPSHOTs.

**Comment by tobias** [comment]
I suspect the change to that :group regex to exclude `\.` was made for consistency, since the commit was an attempt to make the two routes consistent. I don't think it would be a problem to revert that one change.

**Comment by tobias** [comment]
The proper fix for this https://github.com/ato/clojars-web/commit/a477088ff44552c6372034e62257bc33481d837b
