### ISSUE TITLE
Private libraries

### ISSUE THREAD

**Issue by podviaznikov** [ato/clojars-web#323]
Can I store private libraries in Clojars? Would someone be able to get source code if I publish private module to Clojars?

**Comment by tobias** [comment]
Everything deployed to Clojars is publicly available, so if you publish source code in a jar, people will be able to access it. If you need a shared private repo, you can run your own Clojars internally, or use [Archiva](https://archiva.apache.org/index.cgi).

**Comment by podviaznikov** [comment]
Thanks!
