### ISSUE TITLE
account deletion

### ISSUE THREAD

**Issue by devlinzed** [ato/clojars-web#328]
Can you delete my account devlinzed?  Thank you.

**Comment by tobias** [comment]
Deleting your account will remove all of your artifacts (preamble, similarto, and tastekid), which is a bad idea if anyone is depending on them. If you are positive you want to delete the account, please send an email to contact@clojars.org signed with the gpg key registered with your clojars account, or attach a file containing "delete my clojars account" that has been encrypted with that same key.

**Comment by devlinzed** [comment]
I don't have the key any longer and nobody is using those libraries.  Refer to my earlier issue (from a year ago) where I mentioned this concern. https://github.com/ato/clojars-web/issues/205

**Comment by tobias** [comment]
I'm trying to confirm that you are the owner of the devlinzed account. Let's try this: can you change the user metadata on your ssh key at https://clojars.org/profile to "delete@me" (it's currently "devlin@pirates")?

**Comment by devlinzed** [comment]
Yes, I've made that change. Thanks for the reply, @tobias.

**Comment by tobias** [comment]
Thanks, your account, jars, and groups have been deleted.
