### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by jtmarmon** [ato/clojars-web#329]
Can you please take down jtmarmon/cloak. I'd like to have it under our organization account: homeswipe.

If you could transfer ownership to homeswipe that would be fine as well. i'll be signing it with the same gpg key

**Comment by tobias** [comment]
Cloak is under the cloak group (https://clojars.org/groups/cloak). As the owner of that group, you can add the homeswipe account as a member of the group as well, and that account would then have rights to deploy cloak. Will that work for you?

**Comment by jtmarmon** [comment]
I'd like to have the dependency listed as `homeswipe/cloak` rather than `cloak/cloak`.

**Comment by tobias** [comment]
Ah, in that case, you'll need to deploy it as `homeswipe/cloak`, and I can delete `cloak/cloak`. Please confirm that's what you want me to do.

**Comment by jtmarmon** [comment]
yes please. thank you!

**Comment by tobias** [comment]
The `cloak` group has been deleted, along with all of its artifacts.
