### ISSUE TITLE
Please update favicon

### ISSUE THREAD

**Issue by dubiousdavid** [ato/clojars-web#333]
Please update the favicon on clojars.org to correspond with the logo here: https://clojars.org/images/clojars-logo-small.png.

**Comment by tobias** [comment]
This should be a simple change to https://github.com/ato/clojars-web/tree/master/src/clojars/web/common.clj#L40. Thanks for noticing it was missing.

**Comment by tobias** [comment]
I used a [square crop](https://github.com/ato/clojars-web/blob/master/resources/public/favicon.png) of the logo since the icon needs to be square, and the full image gets squashed to fit a square. I'm happy to put something better there if someone were to provide it.
