### ISSUE TITLE
Include clojure.* libraries?!

### ISSUE THREAD

**Issue by jakubholynet** [ato/clojars-web#334]
Hi,

I always find it confusing that some libraries such as `clojure.data.csv` are not in clojars as I considered it to be the one-to-go source of all clojure libraries. Is that on purpose and do I need to use search.maven.org in addition? It would be nice to have those libs here as well.

Thank you!

**Comment by tobias** [comment]
There's not much we can do about that, even if we wanted to - it's up to project authors to deploy their projects where they see fit.

**Comment by jakubholynet** [comment]
Oh, ok, thank you. I will try to take contact with the projects in question
then.

2015-05-06 20:51 GMT+02:00 Toby Crawley <notifications@github.com>:

> There's not much we can do about that, even if we wanted to - it's up to
> project authors to deploy their projects where they see fit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ato/clojars-web/issues/334#issuecomment-99571832>.
>



-- 
*Forget software. Strive to make an impact, deliver a valuable change.*

*(**Vær så snill og hjelp meg med å forbedre norsken **min –** skriftlig og
muntlig. Takk!**)*

Jakub Holy
Solutions Engineer | +47 966 23 666
Iterate AS | www.iterate.no
The Lean Software Development Consultancy
- http://theholyjava.wordpress.com/ -
