### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by roti** [ato/clojars-web#347]
Hi,

I accidentally uploaded a wrong jar file. Uploading the same artifact twice is apparently not allowed:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project swt-win32-win32-x86_64: Failed to deploy ar
tifacts: Could not transfer artifact org.clojars.roti:swt-win32-win32-x86_64:jar:4.4.2 from/to clojars (https://clojars.org/repo): Access denied to: https://clo
jars.org/repo/org/clojars/roti/swt-win32-win32-x86_64/4.4.2/swt-win32-win32-x86_64-4.4.2.jar, ReasonPhrase:Forbidden. -> [Help 1]
```

Therefore, please remove `[org.clojars.roti/swt-gtk-linux-x86_64 "4.4.2"]`, so that I can upload it again. You may remove the entire project if it's easier, it is used only by me, and I care only about the most recent version.

Thank You,
roti

**Comment by tobias** [comment]
I deleted ` [org.clojars.roti/swt-gtk-linux-x86_64 "4.4.2"]` (just that version), so you should be able to redeploy it now.

**Comment by tobias** [comment]
Hmm, the error message refers to `swt-win32-win32-x86_64`, but you requested deletion of the linux variant. Do you actually need the win32 variant deleted instead?

**Comment by roti** [comment]
Yes, thank you for noticing. I need `swt-win32-win32-x86_64` deleted, not `swt-gtk-linux-x86_64`. I apologize for the mistake.
Therefore please delete `[org.clojars.roti/swt-win32-win32-x86_64 "4.4.2"]`.
Also thank you for the quick reaction.

**Comment by tobias** [comment]
I deleted `[org.clojars.roti/swt-win32-win32-x86_64 "4.4.2"]`.
