### ISSUE TITLE
Please reset the email address

### ISSUE THREAD

**Issue by neotyk** [ato/clojars-web#349]
Please reset my email address.
Account used for registering is not available anymore and can't recover the password.

User: https://clojars.org/users/neotyk
Project I need to edit: https://clojars.org/http.async.client
Email: as listed on github: https://github.com/neotyk, alex [at] happyhacking [dot] nl

Cheers,
Alex

**Comment by tobias** [comment]
I updated your email address, you should now be able to reset your password.

**Comment by neotyk** [comment]
Thank you @tobias
