### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by daveyarwood** [ato/clojars-web#354]
Hi,

Please delete this clojar: https://clojars.org/midi.soundfont.fluid-r3

I didn't realize there was a 20 MB limit on clojars -- this project is a packaging of the 141 MB FluidR3 MIDI soundfont. I was not able to successfully deploy the clojar due to the size limit (I got an access denied/forbidden exception), so the repo is currently in a weird state, which has also prevented me from making the description say "delete me"... I hope this is not a problem.

Thanks!

**Comment by tobias** [comment]
No problem, the `midi.soundfont.fluid-r3` group has been deleted, along with all of its artifacts.
