### ISSUE TITLE
Password re-set email not sent

### ISSUE THREAD

**Issue by stumitchell** [ato/clojars-web#363]
I have been trying to log into my day8-clojure@stuartmitchell.com account.

The password reset email is never sent.

Stu

**Comment by tobias** [comment]
There is no account on clojars that has "day8-clojure@stuartmitchell.com" as its username or email. There is a "stumitchell" account that has an email address at the "stuartmitchell.com" domain, can you try that one?

**Comment by stumitchell** [comment]
Thats strange because the user is there https://clojars.org/users/day8

I set this up as an account where I can share it with other people in my organisation. The "stumitchell" account is my private one.

We would like to retain control of this account if possible

Stu

**Comment by tobias** [comment]
The "day8" account doesn't have a "stuartmitchell.com" email - it has a "day8.com.au" address instead. I'm reluctant to share the full email address here, but it appears to belong to Mike Thompson. Do you have access to that email account?

**Comment by stumitchell** [comment]
Right he must have changed it, and forgotten to tell me. Thats egg on my
face :( .Thank you very much for helping us resolve this internal problem.

Stu

**Comment by tobias** [comment]
Glad to help!
