### ISSUE TITLE
Use the http status message to relay more context on deploy failure

### ISSUE THREAD

**Issue by tobias** [ato/clojars-web#367]
Currently, reploying a non-SNAPSHOT, or deploying with an invalid group, project, or version results in:

    Failed to deploy artifacts: Could not transfer artifact blahblah:blahblah:pom:0.1.0 from/to local (https://clojars.org/repo/): Access denied to: http://localhost:8080/repo/blahblah/blahblah/0.1.0/blahblah-0.1.0.pom, ReasonPhrase: Forbidden

It would be nice if we could make that "Forbidden" be "Forbidden - redeploying non-snapshots is not allowed" instead, with similar messages for validation failures.

**Comment by danielcompton** [comment]
It would be good to add a link to docs for further explanation too.

**Comment by tobias** [comment]
Good call, we could link to pages in the wiki.
