### ISSUE TITLE
Point old project at new project?

### ISSUE THREAD

**Issue by mattkeller** [ato/clojars-web#370]
Hi all.

I created https://clojars.org/file-buffer some time ago, but then decided to rename it to https://clojars.org/co.zensight/file-buffer. Both are aimed at the same github project.

Is there a way to redirect users to the current project? Ideally, I'd take down the old project, but in theory people could be depending on it.

Thanks much,
Matt

**Comment by tobias** [comment]
I believe your only option is to push a new SNAPSHOT to the old project, with a new description marking it as deprecated, including a url to the new project. Will that work for you?
