### ISSUE TITLE
Maven Index doesn't include new packages

### ISSUE THREAD

**Issue by reiz** [ato/clojars-web#371]
VersionEye is crawling Cojars once a day to fetch information about new versions and new packages. This here is [Clojure page at VersionEye](https://www.versioneye.com/Clojure). Somehow the new packages doesn't show up anymore. The VersionEye crawler was not changed. And the same crawler is used to crawl other maven repositories. It seems that new packages are not included in the index anymore. Feedback and thoughts on this issue are highly appreciated.

**Comment by tobias** [comment]
`lein` uses the indexes for its search task (via `indexer-core`, I believe), and it can find recent releases:

    $ lein search lein-update-dependency
    Searching over Artifact ID...
    == Showing page 1 / 1
    [lein-update-dependency "0.1.0"] Programmatically update a Leiningen dependency

`lein-update-dependency` had its first release today, so shouldn't be in the index if it is broken. 

Do you know when the results stopped showing up for you? Is it possible you have a corrupted index locally? I have no idea how that would behave.

**Comment by reiz** [comment]
OK. That helps me. I will debug that on my site. Thx.

**Comment by tobias** [comment]
My pleasure! Feel free to reopen if you discover it is indeed an issue with clojars.

**Comment by reiz** [comment]
It was an issue on our side and it's fixed now.

**Comment by tobias** [comment]
Great, thanks for the followup.
