### ISSUE TITLE
Deletion request: org.clojars.triss/midi-data 0.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by triss** [ato/clojars-web#378]
Hi,

If you could remove org.clojars.triss/midi-data *0.2.1-SNAPSHOT* at some point it'd be very much appreciated.

I screwed up the versioning of my project when deploying. 

Many thanks,
Tristan

**Comment by tobias** [comment]
Version `0.2.1-SNAPSHOT` of `org.clojars.triss/midi-data` has been deleted.
