### ISSUE TITLE
Insecure Password Change Mechanism

### ISSUE THREAD

**Issue by shawarkhan52** [ato/clojars-web#383]

**Comment by danielcompton** [comment]
@shawarkhan52 security vulnerabilities should be reported through https://clojars.org/security

**Comment by shawarkhan52** [comment]
i have reported there but i think their email is having some problem so they can't be reached.

**Comment by nberger** [comment]
I was going to say that a responsible disclosure would have been to contact the project maintainers via the "Contact" link in clojars.org footer, which takes to https://github.com/ato/clojars-web/wiki/Contact, which in turn shows contact@clojars.org as the email address.

Didn't see that /security link, that's even better and it's two links to the right of /contact :)

**Comment by shawarkhan52** [comment]
can you please forward this to the security team? email is not sending to contact@clojars.org

**Comment by nberger** [comment]
If that was the case you could have created an issue here saying something like "Hey, I want to report a security issue but your email isn't working. Is there an alternative way to report a security issue?"

**Comment by shawarkhan52** [comment]
okay i will create an issue like that

**Comment by tobias** [comment]
@shawarkhan52 - I got your report, I just haven't had the chance to reply to it. Clojars is a volunteer effort, and I haven't yet been able to devote the time to go through the backlog of emails. Your issue has already been reported (#177), but hasn't yet been fixed.

**Comment by tobias** [comment]
Closing as a dupe of #177.
