### ISSUE TITLE
Deletion request: re-frame 0.5.0

### ISSUE THREAD

**Issue by danielcompton** [ato/clojars-web#392]
I ran `lein release :alpha` as the documentation suggests, to release an alpha, but it released a full version. Are you able to remove re-frame 0.5.0 please? Sorry for the hassle.

https://clojars.org/re-frame

**Comment by tobias** [comment]
Version `0.5.0` of `re-frame` has been deleted.

**Comment by danielcompton** [comment]
Thanks!
