### ISSUE TITLE
Mirroring clojars with Nexus gives an empty repo

### ISSUE THREAD

**Issue by stephanecollot** [ato/clojars-web#397]
Hello,

I would like to know if it is possible to mirror clojars.org/repo with Nexus. From what I saw in the documentation it is a standard Maven2 format repository, and my question is indeed in the FAQ, but it is not working:

Here is my configuration of Nexus (the screenshot is for conjars, but it is the same behaviors for clojars)
![conf](https://cloud.githubusercontent.com/assets/1184396/10661790/6b1ac64e-78b0-11e5-9d20-e26faf04031e.png)

Here is the status
![status](https://cloud.githubusercontent.com/assets/1184396/10661793/6e5ae62c-78b0-11e5-8f8f-0d180c21afbd.png)

And when I go to http://10.****/nexus/content/repositories/conjars-release/ there is only one file, archetype-catalog.xml

Is there a bug in clojars, or did I miss configure something?
Thanks for your help

**Comment by danielcompton** [comment]
I'm not too familiar with mirroring, but is it possible that dependencies will only be stored in your mirror after they are requested for the first time?

**Comment by tobias** [comment]
I've never mirrored a maven repo (clojars or other), so don't know the specifics, but agree with @danielcompton - the "Repository Type: proxy" in your image makes me think it would proxy and cache on request.

**Comment by tobias** [comment]
@stephanecollot - I'm closing this, feel free to reopen if our reasoning above turns out to be incorrect and you need more help.
