### ISSUE TITLE
clojars.org can't be accessed in China

### ISSUE THREAD

**Issue by faywong** [ato/clojars-web#405]
When i try to update the dependencies, it prompts:
```bash
faywong@faywongdeMacBook-Air:~/devel/crawler$ lein run -dev
十月 29, 2015 1:37:14 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {s}->https://clojars.org:443: Connection reset
十月 29, 2015 1:37:14 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {s}->https://clojars.org:443
```
After i import the certificate of clojars.org into my java cacerts, i got this exception:
```bash
信息: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
十月 29, 2015 2:02:20 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {s}->https://clojars.org:443
十月 29, 2015 2:03:35 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clojars.org:443: No route to host
十月 29, 2015 2:03:35 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {s}->https://clojars.org:443
```

then i ping the clojars.org:
```bash
$ ping clojars.org
PING clojars.org (173.230.139.200): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
```

This problem re-produces frequently, so is there an alternative mirror to host the libraries?

**Comment by tobias** [comment]
We haven't had other reports of difficulties connecting (other than an incident that occurred after you filed this issue, due to https://linode.statuspage.io/incidents/nrn56yr4mz23) Do you see this error with other sites? Or when you are on other networks?

I don't know of any public mirrors of clojars, unfortunately. We plan to set up a read-only mirror at some point in the future, in a different data center. Maybe that will help.

**Comment by faywong** [comment]
I have figured it out that some DNS server in China can't resolve the clojars.org caused this problem. Anyway, thanks a lot.
