### ISSUE TITLE
Promoting release times out

### ISSUE THREAD

**Issue by muhuk** [ato/clojars-web#407]
I am trying to promote a [library](https://clojars.org/ring-transit-middleware) but it fails with the following message after a while:

    504 Gateway Time-out
    nginx

**Comment by tobias** [comment]
I suspect is was related to the linode outage yesterday (see https://github.com/ato/clojars-web/issues/406). Can you try again?

**Comment by muhuk** [comment]
Forgot about this. It works now. Thanks!
