### ISSUE TITLE
mount: remove particular versions

### ISSUE THREAD

**Issue by tolitius** [ato/clojars-web#414]
project: https://github.com/tolitius/mount
versions: https://clojars.org/mount/versions

there was a glitch, and multiple versions got released when they should not have. Can you please 

## remove

`0.1.2`
`0.1.3-SNAPSHOT`
`0.2.0-SNAPSHOT`

## leave

`0.1.0-SNAPSHOT`
`0.1.0`
`0.1.1`
`0.1.2-SNAPSHOT`

Thank you!

**Comment by tobias** [comment]
Versions `0.1.2`, `0.1.3-SNAPSHOT`, and `0.2.0-SNAPSHOT` have been deleted.

**Comment by tolitius** [comment]
thank you
